CREATE DATABASE ClinicaUTN
GO
use ClinicaUTN
GO
CREATE TABLE CONTACTO (
	IDCONTACTO INT IDENTITY(1,1) PRIMARY KEY,
	DIRECCION VARCHAR (50) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL, 
	TELEFONO INT NOT NULL
)
GO
CREATE TABLE USUARIO (
	IDUSUARIO INT IDENTITY (1,1) PRIMARY KEY,
	USUARIO VARCHAR UNIQUE NOT NULL,
	CONTRASEÑA VARCHAR (50) NOT NULL,
	CONSTRAINT CHK_USUARIO CHECK (
        PATINDEX('%[A-Z]%', USUARIO) > 0 AND  
        PATINDEX('%[0-9]%', USUARIO) > 0      
    )
)
GO
CREATE TABLE PERSONA (
	IDPERSONA INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR (50),
	APELLIDO VARCHAR (50),
	IDCONTACTO INT NOT NULL,
	FECHA_NAC DATE NOT NULL,
	DNI INT NOT NULL,
	CONSTRAINT FK_CONTACTO FOREIGN KEY (IDCONTACTO) REFERENCES CONTACTO(IDCONTACTO)
)
GO
CREATE TABLE PACIENTE (
	IDPERSONA INT NOT NULL,
	IDUSUARIO INT NOT NULL,
	ESTADO  BIT DEFAULT 1 
)
GO
CREATE TABLE INSTITUCION (
	IDINSTITUCION TINYINT IDENTITY (1,1) PRIMARY KEY,
	FECHA_APERTURA DATE,
	NOMBRE_INSTITUCION VARCHAR (50) NOT NULL,
	DIRECCION VARCHAR (50) NOT NULL
)
GO
CREATE TABLE ESPECIALIDAD (
	IDESPECIALIDAD BIGINT IDENTITY (1,1) PRIMARY KEY,
	ESPECIALIDAD VARCHAR (50)
)
GO
CREATE TABLE PROFESIONAL (
	IDPROFESIONAL INT IDENTITY (1,1) PRIMARY KEY,
	IDUSUARIO INT NOT NULL,
	IDPERSONA INT NOT NULL,
	IDESPECIALIDAD BIGINT NOT NULL,
	ESTADO BIT DEFAULT 1,
	FECHA_INGRESO DATETIME NOT NULL,
	MATRICULA INT UNIQUE NOT NULL,
	IDINSTITUCION TINYINT NOT NULL,
	CONSTRAINT FK_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
	CONSTRAINT FK_PERSONA FOREIGN KEY (IDPERSONA) REFERENCES PERSONA(IDPERSONA),
	CONSTRAINT FK_ESPECIALIDAD FOREIGN KEY (IDESPECIALIDAD) REFERENCES ESPECIALIDAD(IDESPECIALIDAD),
	CONSTRAINT FK_INSTITUCION FOREIGN KEY (IDINSTITUCION) REFERENCES INSTITUCION(IDINSTITUCION)
)
GO
CREATE TABLE TURNO (
	IDTURNO INT IDENTITY (1,1) PRIMARY KEY,
	FECHA DATE NOT NULL,
	HORARIO TIME NOT NULL,
	IDPACIENTE INT NOT NULL,
	IDPROFESIONAL INT NOT NULL,
	IDESPECIALIDAD BIGINT NOT NULL,
	ESTADO VARCHAR (15) NOT NULL,
	OBSERVACIONES VARCHAR (250) NULL
)
	